kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image:  kindest/node:v1.23.17
  extraMounts:
  - hostPath: /Users/tsai/Downloads/kind/kube-scheduler
    containerPath: /root/mount
- role: worker
  image: kindest/node:v1.23.17
  extraMounts:
  - hostPath: /Users/tsai/Downloads/kind/kube-scheduler
    containerPath: /root/mount
